# Generated by Django 4.0.5 on 2022-06-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=20, null=True)),
                ('code', models.CharField(max_length=7)),
                ('pref_reading', models.TextField()),
                ('city_reading', models.TextField()),
                ('area_reading', models.TextField()),
                ('prefecture', models.TextField()),
                ('city', models.TextField()),
                ('area', models.TextField()),
            ],
        ),
    ]
