# Generated by Django 4.0.5 on 2022-07-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='3fd18ae5dcdbbb9f3cfa3b94cf9fe1d9', max_length=64, unique=True),
        ),
    ]
