# Generated by Django 4.0.5 on 2022-07-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_item_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='f4a3fab5c65141560eb51bd7b92e78a7', max_length=64, unique=True),
        ),
    ]
