# Generated by Django 4.0.5 on 2022-07-14 06:02

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_item_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(default=app.models.slug_maker, max_length=64, unique=True),
        ),
    ]
