# Generated by Django 4.0.5 on 2022-07-17 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_order_total_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'カート'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': '商品'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '注文'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': '注文商品'},
        ),
        migrations.AlterModelTable(
            name='cart',
            table='ecsite_cart',
        ),
        migrations.AlterModelTable(
            name='item',
            table='ecsite_item',
        ),
        migrations.AlterModelTable(
            name='order',
            table='ecsite_order',
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='ecsite_order_item',
        ),
    ]
