# Generated by Django 4.0.5 on 2022-07-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_item_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='168a023beaeac76d11d9f815a2efb463', max_length=64, unique=True),
        ),
    ]
