# Generated by Django 4.0.5 on 2022-07-17 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_cart_options_alter_item_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'カート', 'verbose_name_plural': 'カート'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '注文', 'verbose_name_plural': '注文'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': '注文商品', 'verbose_name_plural': '注文商品'},
        ),
    ]
