# Generated by Django 4.0.5 on 2022-07-17 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '注文明細', 'verbose_name_plural': '注文明細'},
        ),
    ]
