# Generated by Django 4.0.5 on 2022-07-03 12:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_payment_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='730cec8ea926fef9b705896efb96c978', max_length=64, unique=True),
        ),
    ]
