# Generated by Django 4.0.5 on 2022-07-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_item_quantity_alter_item_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='456d0095cf70ee6fb0c4e734b2cc82e6', max_length=64, unique=True),
        ),
    ]
