# Generated by Django 4.0.5 on 2022-07-07 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_item_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='6c89bdab5dcf7679feb43d2980ebf168', max_length=64, unique=True),
        ),
    ]
