# Generated by Django 4.0.5 on 2022-07-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_item_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='stripe_charge_id',
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='854aac71a8ffe21d497e4a33f439967d', max_length=64, unique=True),
        ),
    ]
