# Generated by Django 4.0.5 on 2022-06-22 12:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_created_alter_customuser_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='入会日'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, max_length=30, verbose_name='所属'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='名'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='姓'),
        ),
    ]
